// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _numadd_HH_
#define _numadd_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "numadd_add_io_s_axi.h"

namespace ap_rtl {

template<unsigned int C_S_AXI_ADD_IO_ADDR_WIDTH = 6,
         unsigned int C_S_AXI_ADD_IO_DATA_WIDTH = 32>
struct numadd : public sc_module {
    // Port declarations 23
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_logic > s_axi_add_io_AWVALID;
    sc_out< sc_logic > s_axi_add_io_AWREADY;
    sc_in< sc_uint<C_S_AXI_ADD_IO_ADDR_WIDTH> > s_axi_add_io_AWADDR;
    sc_in< sc_logic > s_axi_add_io_WVALID;
    sc_out< sc_logic > s_axi_add_io_WREADY;
    sc_in< sc_uint<C_S_AXI_ADD_IO_DATA_WIDTH> > s_axi_add_io_WDATA;
    sc_in< sc_uint<C_S_AXI_ADD_IO_DATA_WIDTH/8> > s_axi_add_io_WSTRB;
    sc_in< sc_logic > s_axi_add_io_ARVALID;
    sc_out< sc_logic > s_axi_add_io_ARREADY;
    sc_in< sc_uint<C_S_AXI_ADD_IO_ADDR_WIDTH> > s_axi_add_io_ARADDR;
    sc_out< sc_logic > s_axi_add_io_RVALID;
    sc_in< sc_logic > s_axi_add_io_RREADY;
    sc_out< sc_uint<C_S_AXI_ADD_IO_DATA_WIDTH> > s_axi_add_io_RDATA;
    sc_out< sc_lv<2> > s_axi_add_io_RRESP;
    sc_out< sc_logic > s_axi_add_io_BVALID;
    sc_in< sc_logic > s_axi_add_io_BREADY;
    sc_out< sc_lv<2> > s_axi_add_io_BRESP;
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst_n;
    sc_signal< sc_logic > ap_var_for_const0;
    // Port declarations for the virtual clock. 
    sc_in_clk ap_virtual_clock;


    // Module declarations
    numadd(sc_module_name name);
    SC_HAS_PROCESS(numadd);

    ~numadd();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    numadd_add_io_s_axi<C_S_AXI_ADD_IO_ADDR_WIDTH,C_S_AXI_ADD_IO_DATA_WIDTH>* numadd_add_io_s_axi_U;
    sc_signal< sc_lv<32> > a;
    sc_signal< sc_lv<32> > b;
    sc_signal< sc_lv<32> > y;
    sc_signal< sc_logic > y_ap_vld;
    sc_signal< sc_logic > ap_rst_n_inv;
    static const sc_logic ap_const_logic_1;
    static const int C_S_AXI_DATA_WIDTH;
    static const sc_logic ap_const_logic_0;
    // Thread declarations
    void thread_ap_var_for_const0();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_rst_n_inv();
    void thread_y();
    void thread_y_ap_vld();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
