// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xnumadd.h"

extern XNumadd_Config XNumadd_ConfigTable[];

XNumadd_Config *XNumadd_LookupConfig(u16 DeviceId) {
	XNumadd_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XNUMADD_NUM_INSTANCES; Index++) {
		if (XNumadd_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XNumadd_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XNumadd_Initialize(XNumadd *InstancePtr, u16 DeviceId) {
	XNumadd_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XNumadd_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XNumadd_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

