// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef XNUMADD_H
#define XNUMADD_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xnumadd_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Add_io_BaseAddress;
} XNumadd_Config;
#endif

typedef struct {
    u32 Add_io_BaseAddress;
    u32 IsReady;
} XNumadd;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XNumadd_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XNumadd_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XNumadd_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XNumadd_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XNumadd_Initialize(XNumadd *InstancePtr, u16 DeviceId);
XNumadd_Config* XNumadd_LookupConfig(u16 DeviceId);
int XNumadd_CfgInitialize(XNumadd *InstancePtr, XNumadd_Config *ConfigPtr);
#else
int XNumadd_Initialize(XNumadd *InstancePtr, const char* InstanceName);
int XNumadd_Release(XNumadd *InstancePtr);
#endif


void XNumadd_Set_a(XNumadd *InstancePtr, u32 Data);
u32 XNumadd_Get_a(XNumadd *InstancePtr);
void XNumadd_Set_b(XNumadd *InstancePtr, u32 Data);
u32 XNumadd_Get_b(XNumadd *InstancePtr);
u32 XNumadd_Get_y(XNumadd *InstancePtr);
u32 XNumadd_Get_y_vld(XNumadd *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
