# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir H:/viv/numadd/numadd.cache/wt [current_project]
set_property parent.project_path H:/viv/numadd/numadd.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths h:/viv/numadd_hls/solution1/impl [current_project]
add_files H:/viv/numadd/numadd.srcs/sources_1/bd/design_1/design_1.bd
set_property used_in_implementation false [get_files -all h:/viv/numadd/numadd.srcs/sources_1/bd/design_1/ip/design_1_numadd_0_0/constraints/numadd_ooc.xdc]
set_property used_in_implementation false [get_files -all h:/viv/numadd/numadd.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all h:/viv/numadd/numadd.srcs/sources_1/bd/design_1/ip/design_1_rst_processing_system7_0_50M_0/design_1_rst_processing_system7_0_50M_0_board.xdc]
set_property used_in_implementation false [get_files -all h:/viv/numadd/numadd.srcs/sources_1/bd/design_1/ip/design_1_rst_processing_system7_0_50M_0/design_1_rst_processing_system7_0_50M_0.xdc]
set_property used_in_implementation false [get_files -all h:/viv/numadd/numadd.srcs/sources_1/bd/design_1/ip/design_1_rst_processing_system7_0_50M_0/design_1_rst_processing_system7_0_50M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all h:/viv/numadd/numadd.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all H:/viv/numadd/numadd.srcs/sources_1/bd/design_1/design_1_ooc.xdc]
set_property is_locked true [get_files H:/viv/numadd/numadd.srcs/sources_1/bd/design_1/design_1.bd]

read_verilog -library xil_defaultlib H:/viv/numadd/numadd.srcs/sources_1/bd/design_1/hdl/design_1_wrapper.v
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top design_1_wrapper -part xc7z020clg400-1


write_checkpoint -force -noxdef design_1_wrapper.dcp

catch { report_utilization -file design_1_wrapper_utilization_synth.rpt -pb design_1_wrapper_utilization_synth.pb }
